"""Add user_id to session

Revision ID: c257094f622b
Revises: 
Create Date: 2024-05-27 18:31:52.864463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c257094f622b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Sessions_id', table_name='Sessions')
    op.drop_table('Sessions')
    op.drop_table('User')
    op.drop_index('ix_Messages_id', table_name='Messages')
    op.drop_table('Messages')
    op.add_column('documents', sa.Column('document_name', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_content', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.add_column('queries', sa.Column('query_text', sa.String(), nullable=True))
    op.add_column('queries', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('query_response', sa.String(), nullable=True))
    op.add_column('queries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_queries_id'), 'queries', ['id'], unique=False)
    op.create_foreign_key(None, 'queries', 'sessions', ['session_id'], ['id'])
    op.add_column('sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'user_id')
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_index(op.f('ix_queries_id'), table_name='queries')
    op.drop_column('queries', 'created_at')
    op.drop_column('queries', 'query_response')
    op.drop_column('queries', 'session_id')
    op.drop_column('queries', 'query_text')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_column('documents', 'document_content')
    op.drop_column('documents', 'document_name')
    op.create_table('Messages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Messages_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('messageText', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Messages_pkey')
    )
    op.create_index('ix_Messages_id', 'Messages', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_table('Sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sessions_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('sessionName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Sessions_pkey')
    )
    op.create_index('ix_Sessions_id', 'Sessions', ['id'], unique=False)
    # ### end Alembic commands ###
